#!/usr/bin/env bash
# installs and configs HAproxy
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy
FILE=/etc/haproxy/haproxy.cfg
echo -e "frontend web-frontend
\tbind *:80
\tmode http
\tdefault_backend web_backend
backend web_backend
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver web-01 35.243.141.236:80 check
\tserver web-02 35.229.67.20:80 check" | sudo tee -a $FILE
sudo service haproxy restart
