#!/usr/bin/env bash
# this script is to display "Holberton School" with a while loop
end=20
i=0
while ((i<=end)); do 
((i=i+1))
echo $i
case $i in
	4)
	echo "bad luck from China "
	;;
	9)
	echo "bad luck from Japan"
	;;
	17)
	echo "bad luck from Italy"
	;;
esac
done
