#!/usr/bin/env bash
#checks if file exist
if [ -e "holbertonschool" ]
then
	echo "holbertonschool file exists"
	if [ -s "holbertonschool" ]
	then
		echo "holbertonschool file is not empty"
		if [ ! -d "holbertonschool" ]
		then
			echo "holbertonschool is a regular file"
		fi
	else
		echo "holbertonschool file is empty"
		if [ ! -d "holbertonschool" ]
		then
			echo "holbertonschool is a regular file"
		fi
	fi
else
	echo "holbertonschool file does not exist"

fi
